debug: true

database:
  log_queries: true
  timeout_seconds: 5
  psn: postgres://localhost:5432/postgres
  mysql: root:toor@/depp?charset=utf8&parseTime=True&loc=Local

redis:
  host: 127.0.0.1
  port: :6379
  password: ZjY0ZWM0MDVhYjM2NmY4MTIzNGQ5OTFi
  lifetime:
    access: 1209600
    refresh: 1209600
    apps: 45
  prefix:
    access: depp_access
    refresh: depp_refresh
    apps: dep_apps

server:
  port: :8080
  debug: true
  read_timeout_seconds: 10
  write_timeout_seconds: 5

application:
  min_password_strength: 1
  swagger_ui_path: assets/swaggerui